# Site settings
title: Posts
subtitle: by Keith Reynolds
# email: youremailaddress@gmail.com
description: Writing
baseurl: "/posts" # the subpath of your site, e.g. /blog
url: "https://keithreynolds.me" # the base hostname & protocol for your site
author: Keith Reynolds
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/keithreynolds
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/kpreynolds
pinterest_url:
slack_url:
twitter_url: https://twitter.com/subtlebreaker

# Build settings
markdown: kramdown
